services:
  casa:
    image: ghcr.io/zamaruu/casa:tag
    container_name: casa
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
      - DB_TYPE=mongo
      - DB_CONNECTION_STRING=mongodb://localhost:27017/casa
      - JWT_SECRET=changeme
      - JWT_EXPIRES_IN=48