name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.5
  lints: ^6.0.0
  test: ^1.25.6
