name: api
description: A server app using the shelf package and Docker.
version: 1.0.0
export_to: 'none'
# repository: https://github.com/my_org/my_repo


environment:
  sdk: ^3.10.4

dependencies:
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  jose: ^0.3.4
  http: ^1.2.0
  shared:
    path: ../shared
  mongo_dart: ^0.10.5
  get_it: ^9.2.0
  dotenv: ^4.2.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
